type User @table {
  displayName: String!
  createdAt: Timestamp!
  email: String!
  avatarUrl: String
  currencyBalance: Int!
}

type StudySession @table {
  startTime: Timestamp!
  endTime: Timestamp!
  subject: Subject
  workBlockMs: Int!
  breakBlockMs: Int!
  intendedCycles: Int
  durationMs: Int!
  productivityRating: Int
  createdAt: Timestamp!
  reflections: String
  earnedCurrency: Int
  user: User!
}

type Subject @table {
  name: String!
  createdAt: Timestamp!
  description: String
  icon: String
  user: User!
}