query Me @auth(level: USER) {
  user(key: { id_expr: "auth.uid" }) {
    id
    displayName
    currencyBalance
    createdAt
  }
}

query MySubjects @auth(level: USER) {
  subjects(where: { userId: { eq: "auth.uid" } }) {
    id
    name
    createdAt
  }
}

query MyStudySessions(
  $subjectId: UUID,
  $startAfter: Timestamp,
  $startBefore: Timestamp,
  $limit: Int = 1000
) @auth(level: USER) {
  studySessions(
    where: {
      userId: { eq: "auth.uid" },
      subjectId: { eq: $subjectId },
      startTime: { gt: $startAfter, lt: $startBefore }
    },
    orderBy: { startTime: DESC },
    limit: $limit
  ) {
    id
    startTime
    endTime
    workBlockMs
    breakBlockMs
    intendedCycles
    productivityRating
    reflections
    earnedCurrency
    subject {
      id
      name
    }
  }
}

mutation CreateUser($displayName: String!) @auth(level: PUBLIC) {
  user_insert(
    data: {
      displayName: $displayName
    }
  )
}         

mutation CreateSubject($name: String!) @auth(level: USER) {
  subject_insert(
    data: {
      name: $name
      userId_expr: "auth.uid"
      createdAt_expr: "request.time"
    }
  )
}

mutation CreateStudySession(
  $subjectId: UUID!,
  $startTime: Timestamp!,
  $endTime: Timestamp!,
  $workBlockMs: Int!,
  $breakBlockMs: Int!,
  $intendedCycles: Int,
  $productivityRating: Int,
  $reflections: String,
  $earnedCurrency: Int!,
) @auth(level: USER) {
  studySession_insert(
    data: {
      subjectId: $subjectId,
      userId_expr: "auth.uid",
      createdAt_expr: "request.time",
      startTime: $startTime,
      endTime: $endTime,
      workBlockMs: $workBlockMs,
      breakBlockMs: $breakBlockMs,
      intendedCycles: $intendedCycles,
      productivityRating: $productivityRating,
      reflections: $reflections,
      earnedCurrency: $earnedCurrency
    }
  )
}

mutation DeleteStudySession($key: StudySession_Key!) @auth(level: USER) {
  studySession_delete(key: $key)
}

mutation UpdateSubject(
  $key: Subject_Key!,
  $name: String
) @auth(level: USER) {
  subject_update(
    key: $key,
    data: { name: $name }
  )
}

mutation DeleteSubject($key: Subject_Key!) @auth(level: USER) {
  subject_delete(key: $key)
}
