mutation CreateUser @auth(level: USER) {
  user_insert(data: {
    id_expr: "uuidV4()",
    displayName: "New User",
    createdAt_expr: "request.time",
    email_expr: "auth.token.email",
    currencyBalance: 0
  })
}

query ListSubjects @auth(level: USER, insecureReason: "This operation is safe to expose to all logged in users.") {
  subjects {
    id
    name
    description
  }
}

mutation CreateStudySession($subjectId: UUID!, $durationMs: Int!, $endTime: Timestamp!, $productivityRating: Int!, $startTime: Timestamp!) @auth(level: USER) {
  studySession_insert(data: {
    subjectId: $subjectId,
    userId_expr: "auth.uid",
    createdAt_expr: "request.time",
    endTime: $endTime,
    productivityRating: $productivityRating,
    startTime: $startTime,
    workBlockMs: 0,
    breakBlockMs: 0,
    durationMs: $durationMs
  })
}