extend type StudySession {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "StudySession", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `StudySession`.`subject`. It must match the value of `Subject`.`id`. See `@ref` for how to customize it.
  """
  subjectId: UUID @fdc_generated(from: "StudySession.subject", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `StudySession`.`user`. It must match the value of `User`.`id`. See `@ref` for how to customize it.
  """
  userId: UUID! @fdc_generated(from: "StudySession.user", purpose: IMPLICIT_REF_FIELD)
}
extend type Subject {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "Subject", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `Subject`.`user`. It must match the value of `User`.`id`. See `@ref` for how to customize it.
  """
  userId: UUID! @fdc_generated(from: "Subject.user", purpose: IMPLICIT_REF_FIELD)
}
extend type User {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "User", purpose: IMPLICIT_KEY_FIELD)
}
