extend type StudySession {
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "StudySession", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `StudySession` table.
  """
  _count: Int! @fdc_generated(from: "StudySession.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `StudySession` table where the `breakBlockMs` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  breakBlockMs_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "StudySession.breakBlockMs", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `StudySession` table where the `createdAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  createdAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "StudySession.createdAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `StudySession` table where the `durationMs` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  durationMs_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "StudySession.durationMs", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `StudySession` table where the `earnedCurrency` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  earnedCurrency_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "StudySession.earnedCurrency", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `StudySession` table where the `endTime` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  endTime_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "StudySession.endTime", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `StudySession` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "StudySession.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `StudySession` table where the `intendedCycles` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  intendedCycles_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "StudySession.intendedCycles", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `StudySession` table where the `productivityRating` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  productivityRating_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "StudySession.productivityRating", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `StudySession` table where the `reflections` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  reflections_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "StudySession.reflections", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `StudySession` table where the `startTime` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  startTime_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "StudySession.startTime", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `StudySession` table where the `subjectId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  subjectId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "StudySession.subjectId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `StudySession` table where the `userId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  userId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "StudySession.userId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `StudySession` table where the `workBlockMs` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  workBlockMs_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "StudySession.workBlockMs", purpose: QUERY_COUNT)
  """
  ✨ Sum the `breakBlockMs` field in the `StudySession` table.
  """
  breakBlockMs_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Int @fdc_generated(from: "StudySession.breakBlockMs", purpose: QUERY_SUM)
  """
  ✨ Sum the `durationMs` field in the `StudySession` table.
  """
  durationMs_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Int @fdc_generated(from: "StudySession.durationMs", purpose: QUERY_SUM)
  """
  ✨ Sum the `earnedCurrency` field in the `StudySession` table.
  """
  earnedCurrency_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Int @fdc_generated(from: "StudySession.earnedCurrency", purpose: QUERY_SUM)
  """
  ✨ Sum the `intendedCycles` field in the `StudySession` table.
  """
  intendedCycles_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Int @fdc_generated(from: "StudySession.intendedCycles", purpose: QUERY_SUM)
  """
  ✨ Sum the `productivityRating` field in the `StudySession` table.
  """
  productivityRating_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Int @fdc_generated(from: "StudySession.productivityRating", purpose: QUERY_SUM)
  """
  ✨ Sum the `workBlockMs` field in the `StudySession` table.
  """
  workBlockMs_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Int @fdc_generated(from: "StudySession.workBlockMs", purpose: QUERY_SUM)
  """
  ✨ Average the `breakBlockMs` field in the `StudySession` table.
  """
  breakBlockMs_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "StudySession.breakBlockMs", purpose: QUERY_AVG)
  """
  ✨ Average the `durationMs` field in the `StudySession` table.
  """
  durationMs_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "StudySession.durationMs", purpose: QUERY_AVG)
  """
  ✨ Average the `earnedCurrency` field in the `StudySession` table.
  """
  earnedCurrency_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "StudySession.earnedCurrency", purpose: QUERY_AVG)
  """
  ✨ Average the `intendedCycles` field in the `StudySession` table.
  """
  intendedCycles_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "StudySession.intendedCycles", purpose: QUERY_AVG)
  """
  ✨ Average the `productivityRating` field in the `StudySession` table.
  """
  productivityRating_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "StudySession.productivityRating", purpose: QUERY_AVG)
  """
  ✨ Average the `workBlockMs` field in the `StudySession` table.
  """
  workBlockMs_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "StudySession.workBlockMs", purpose: QUERY_AVG)
  """
  ✨ Minimum of the `breakBlockMs` field in the `StudySession` table.
  """
  breakBlockMs_min: Int @fdc_generated(from: "StudySession.breakBlockMs", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `createdAt` field in the `StudySession` table.
  """
  createdAt_min: Timestamp @fdc_generated(from: "StudySession.createdAt", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `durationMs` field in the `StudySession` table.
  """
  durationMs_min: Int @fdc_generated(from: "StudySession.durationMs", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `earnedCurrency` field in the `StudySession` table.
  """
  earnedCurrency_min: Int @fdc_generated(from: "StudySession.earnedCurrency", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `endTime` field in the `StudySession` table.
  """
  endTime_min: Timestamp @fdc_generated(from: "StudySession.endTime", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `intendedCycles` field in the `StudySession` table.
  """
  intendedCycles_min: Int @fdc_generated(from: "StudySession.intendedCycles", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `productivityRating` field in the `StudySession` table.
  """
  productivityRating_min: Int @fdc_generated(from: "StudySession.productivityRating", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `startTime` field in the `StudySession` table.
  """
  startTime_min: Timestamp @fdc_generated(from: "StudySession.startTime", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `workBlockMs` field in the `StudySession` table.
  """
  workBlockMs_min: Int @fdc_generated(from: "StudySession.workBlockMs", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `breakBlockMs` field in the `StudySession` table.
  """
  breakBlockMs_max: Int @fdc_generated(from: "StudySession.breakBlockMs", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `createdAt` field in the `StudySession` table.
  """
  createdAt_max: Timestamp @fdc_generated(from: "StudySession.createdAt", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `durationMs` field in the `StudySession` table.
  """
  durationMs_max: Int @fdc_generated(from: "StudySession.durationMs", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `earnedCurrency` field in the `StudySession` table.
  """
  earnedCurrency_max: Int @fdc_generated(from: "StudySession.earnedCurrency", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `endTime` field in the `StudySession` table.
  """
  endTime_max: Timestamp @fdc_generated(from: "StudySession.endTime", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `intendedCycles` field in the `StudySession` table.
  """
  intendedCycles_max: Int @fdc_generated(from: "StudySession.intendedCycles", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `productivityRating` field in the `StudySession` table.
  """
  productivityRating_max: Int @fdc_generated(from: "StudySession.productivityRating", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `startTime` field in the `StudySession` table.
  """
  startTime_max: Timestamp @fdc_generated(from: "StudySession.startTime", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `workBlockMs` field in the `StudySession` table.
  """
  workBlockMs_max: Int @fdc_generated(from: "StudySession.workBlockMs", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "StudySession.id", purpose: GLOBAL_ID)
}
extend type Subject {
  """
  ✨ List `StudySession` objects in a one-to-many relationship (where `StudySession`.`subject` is this object).
  """
  studySessions_on_subject(
    """
    Filter condition to narrow down the query results.
    """
    where: StudySession_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [StudySession_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: StudySession_Having
  ): [StudySession!]! @fdc_generated(from: "StudySession.subject", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "Subject", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `Subject` table.
  """
  _count: Int! @fdc_generated(from: "Subject.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Subject` table where the `createdAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  createdAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Subject.createdAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Subject` table where the `description` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  description_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Subject.description", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Subject` table where the `icon` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  icon_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Subject.icon", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Subject` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Subject.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Subject` table where the `name` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  name_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Subject.name", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Subject` table where the `userId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  userId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Subject.userId", purpose: QUERY_COUNT)
  """
  ✨ Minimum of the `createdAt` field in the `Subject` table.
  """
  createdAt_min: Timestamp @fdc_generated(from: "Subject.createdAt", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `createdAt` field in the `Subject` table.
  """
  createdAt_max: Timestamp @fdc_generated(from: "Subject.createdAt", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "Subject.id", purpose: GLOBAL_ID)
}
extend type User {
  """
  ✨ List `StudySession` objects in a one-to-many relationship (where `StudySession`.`user` is this object).
  """
  studySessions_on_user(
    """
    Filter condition to narrow down the query results.
    """
    where: StudySession_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [StudySession_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: StudySession_Having
  ): [StudySession!]! @fdc_generated(from: "StudySession.user", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  ✨ List `Subject` objects in a one-to-many relationship (where `Subject`.`user` is this object).
  """
  subjects_on_user(
    """
    Filter condition to narrow down the query results.
    """
    where: Subject_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Subject_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Subject_Having
  ): [Subject!]! @fdc_generated(from: "Subject.user", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "User", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `User` table.
  """
  _count: Int! @fdc_generated(from: "User.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `avatarUrl` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  avatarUrl_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.avatarUrl", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `createdAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  createdAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.createdAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `currencyBalance` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  currencyBalance_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.currencyBalance", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `displayName` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  displayName_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.displayName", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `email` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  email_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.email", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.id", purpose: QUERY_COUNT)
  """
  ✨ Sum the `currencyBalance` field in the `User` table.
  """
  currencyBalance_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Int @fdc_generated(from: "User.currencyBalance", purpose: QUERY_SUM)
  """
  ✨ Average the `currencyBalance` field in the `User` table.
  """
  currencyBalance_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "User.currencyBalance", purpose: QUERY_AVG)
  """
  ✨ Minimum of the `createdAt` field in the `User` table.
  """
  createdAt_min: Timestamp @fdc_generated(from: "User.createdAt", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `currencyBalance` field in the `User` table.
  """
  currencyBalance_min: Int @fdc_generated(from: "User.currencyBalance", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `createdAt` field in the `User` table.
  """
  createdAt_max: Timestamp @fdc_generated(from: "User.createdAt", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `currencyBalance` field in the `User` table.
  """
  currencyBalance_max: Int @fdc_generated(from: "User.currencyBalance", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "User.id", purpose: GLOBAL_ID)
}
