extend type StudyGoal {
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "StudyGoal", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `StudyGoal` table.
  """
  _count: Int! @fdc_generated(from: "StudyGoal.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `StudyGoal` table where the `createdAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  createdAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "StudyGoal.createdAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `StudyGoal` table where the `currentValue` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  currentValue_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "StudyGoal.currentValue", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `StudyGoal` table where the `description` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  description_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "StudyGoal.description", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `StudyGoal` table where the `dueDate` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  dueDate_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "StudyGoal.dueDate", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `StudyGoal` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "StudyGoal.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `StudyGoal` table where the `status` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  status_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "StudyGoal.status", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `StudyGoal` table where the `subjectId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  subjectId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "StudyGoal.subjectId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `StudyGoal` table where the `targetValue` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  targetValue_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "StudyGoal.targetValue", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `StudyGoal` table where the `unit` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  unit_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "StudyGoal.unit", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `StudyGoal` table where the `userId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  userId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "StudyGoal.userId", purpose: QUERY_COUNT)
  """
  ✨ Sum the `currentValue` field in the `StudyGoal` table.
  """
  currentValue_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "StudyGoal.currentValue", purpose: QUERY_SUM)
  """
  ✨ Sum the `targetValue` field in the `StudyGoal` table.
  """
  targetValue_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "StudyGoal.targetValue", purpose: QUERY_SUM)
  """
  ✨ Average the `currentValue` field in the `StudyGoal` table.
  """
  currentValue_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "StudyGoal.currentValue", purpose: QUERY_AVG)
  """
  ✨ Average the `targetValue` field in the `StudyGoal` table.
  """
  targetValue_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "StudyGoal.targetValue", purpose: QUERY_AVG)
  """
  ✨ Minimum of the `createdAt` field in the `StudyGoal` table.
  """
  createdAt_min: Timestamp @fdc_generated(from: "StudyGoal.createdAt", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `currentValue` field in the `StudyGoal` table.
  """
  currentValue_min: Float @fdc_generated(from: "StudyGoal.currentValue", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `dueDate` field in the `StudyGoal` table.
  """
  dueDate_min: Date @fdc_generated(from: "StudyGoal.dueDate", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `targetValue` field in the `StudyGoal` table.
  """
  targetValue_min: Float @fdc_generated(from: "StudyGoal.targetValue", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `createdAt` field in the `StudyGoal` table.
  """
  createdAt_max: Timestamp @fdc_generated(from: "StudyGoal.createdAt", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `currentValue` field in the `StudyGoal` table.
  """
  currentValue_max: Float @fdc_generated(from: "StudyGoal.currentValue", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `dueDate` field in the `StudyGoal` table.
  """
  dueDate_max: Date @fdc_generated(from: "StudyGoal.dueDate", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `targetValue` field in the `StudyGoal` table.
  """
  targetValue_max: Float @fdc_generated(from: "StudyGoal.targetValue", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "StudyGoal.id", purpose: GLOBAL_ID)
}
extend type StudySession {
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "StudySession", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `StudySession` table.
  """
  _count: Int! @fdc_generated(from: "StudySession.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `StudySession` table where the `createdAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  createdAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "StudySession.createdAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `StudySession` table where the `durationMinutes` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  durationMinutes_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "StudySession.durationMinutes", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `StudySession` table where the `earnedCurrency` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  earnedCurrency_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "StudySession.earnedCurrency", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `StudySession` table where the `endTime` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  endTime_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "StudySession.endTime", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `StudySession` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "StudySession.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `StudySession` table where the `productivityRating` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  productivityRating_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "StudySession.productivityRating", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `StudySession` table where the `reflections` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  reflections_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "StudySession.reflections", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `StudySession` table where the `startTime` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  startTime_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "StudySession.startTime", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `StudySession` table where the `subjectId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  subjectId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "StudySession.subjectId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `StudySession` table where the `userId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  userId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "StudySession.userId", purpose: QUERY_COUNT)
  """
  ✨ Sum the `durationMinutes` field in the `StudySession` table.
  """
  durationMinutes_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Int @fdc_generated(from: "StudySession.durationMinutes", purpose: QUERY_SUM)
  """
  ✨ Sum the `earnedCurrency` field in the `StudySession` table.
  """
  earnedCurrency_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Int @fdc_generated(from: "StudySession.earnedCurrency", purpose: QUERY_SUM)
  """
  ✨ Sum the `productivityRating` field in the `StudySession` table.
  """
  productivityRating_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Int @fdc_generated(from: "StudySession.productivityRating", purpose: QUERY_SUM)
  """
  ✨ Average the `durationMinutes` field in the `StudySession` table.
  """
  durationMinutes_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "StudySession.durationMinutes", purpose: QUERY_AVG)
  """
  ✨ Average the `earnedCurrency` field in the `StudySession` table.
  """
  earnedCurrency_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "StudySession.earnedCurrency", purpose: QUERY_AVG)
  """
  ✨ Average the `productivityRating` field in the `StudySession` table.
  """
  productivityRating_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "StudySession.productivityRating", purpose: QUERY_AVG)
  """
  ✨ Minimum of the `createdAt` field in the `StudySession` table.
  """
  createdAt_min: Timestamp @fdc_generated(from: "StudySession.createdAt", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `durationMinutes` field in the `StudySession` table.
  """
  durationMinutes_min: Int @fdc_generated(from: "StudySession.durationMinutes", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `earnedCurrency` field in the `StudySession` table.
  """
  earnedCurrency_min: Int @fdc_generated(from: "StudySession.earnedCurrency", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `endTime` field in the `StudySession` table.
  """
  endTime_min: Timestamp @fdc_generated(from: "StudySession.endTime", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `productivityRating` field in the `StudySession` table.
  """
  productivityRating_min: Int @fdc_generated(from: "StudySession.productivityRating", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `startTime` field in the `StudySession` table.
  """
  startTime_min: Timestamp @fdc_generated(from: "StudySession.startTime", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `createdAt` field in the `StudySession` table.
  """
  createdAt_max: Timestamp @fdc_generated(from: "StudySession.createdAt", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `durationMinutes` field in the `StudySession` table.
  """
  durationMinutes_max: Int @fdc_generated(from: "StudySession.durationMinutes", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `earnedCurrency` field in the `StudySession` table.
  """
  earnedCurrency_max: Int @fdc_generated(from: "StudySession.earnedCurrency", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `endTime` field in the `StudySession` table.
  """
  endTime_max: Timestamp @fdc_generated(from: "StudySession.endTime", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `productivityRating` field in the `StudySession` table.
  """
  productivityRating_max: Int @fdc_generated(from: "StudySession.productivityRating", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `startTime` field in the `StudySession` table.
  """
  startTime_max: Timestamp @fdc_generated(from: "StudySession.startTime", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "StudySession.id", purpose: GLOBAL_ID)
}
extend type Subject {
  """
  ✨ List `StudyGoal` objects in a one-to-many relationship (where `StudyGoal`.`subject` is this object).
  """
  studyGoals_on_subject(
    """
    Filter condition to narrow down the query results.
    """
    where: StudyGoal_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [StudyGoal_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: StudyGoal_Having
  ): [StudyGoal!]! @fdc_generated(from: "StudyGoal.subject", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  ✨ List `StudySession` objects in a one-to-many relationship (where `StudySession`.`subject` is this object).
  """
  studySessions_on_subject(
    """
    Filter condition to narrow down the query results.
    """
    where: StudySession_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [StudySession_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: StudySession_Having
  ): [StudySession!]! @fdc_generated(from: "StudySession.subject", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "Subject", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `Subject` table.
  """
  _count: Int! @fdc_generated(from: "Subject.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Subject` table where the `createdAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  createdAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Subject.createdAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Subject` table where the `description` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  description_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Subject.description", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Subject` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Subject.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Subject` table where the `name` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  name_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Subject.name", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Subject` table where the `userId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  userId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Subject.userId", purpose: QUERY_COUNT)
  """
  ✨ Minimum of the `createdAt` field in the `Subject` table.
  """
  createdAt_min: Timestamp @fdc_generated(from: "Subject.createdAt", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `createdAt` field in the `Subject` table.
  """
  createdAt_max: Timestamp @fdc_generated(from: "Subject.createdAt", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "Subject.id", purpose: GLOBAL_ID)
}
extend type User {
  """
  ✨ List `StudyGoal` objects in a one-to-many relationship (where `StudyGoal`.`user` is this object).
  """
  studyGoals_on_user(
    """
    Filter condition to narrow down the query results.
    """
    where: StudyGoal_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [StudyGoal_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: StudyGoal_Having
  ): [StudyGoal!]! @fdc_generated(from: "StudyGoal.user", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  ✨ List `StudySession` objects in a one-to-many relationship (where `StudySession`.`user` is this object).
  """
  studySessions_on_user(
    """
    Filter condition to narrow down the query results.
    """
    where: StudySession_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [StudySession_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: StudySession_Having
  ): [StudySession!]! @fdc_generated(from: "StudySession.user", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  ✨ List `Subject` objects in a one-to-many relationship (where `Subject`.`user` is this object).
  """
  subjects_on_user(
    """
    Filter condition to narrow down the query results.
    """
    where: Subject_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Subject_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Subject_Having
  ): [Subject!]! @fdc_generated(from: "Subject.user", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "User", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `User` table.
  """
  _count: Int! @fdc_generated(from: "User.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `avatarUrl` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  avatarUrl_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.avatarUrl", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `createdAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  createdAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.createdAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `currencyBalance` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  currencyBalance_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.currencyBalance", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `displayName` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  displayName_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.displayName", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `email` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  email_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.email", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.id", purpose: QUERY_COUNT)
  """
  ✨ Sum the `currencyBalance` field in the `User` table.
  """
  currencyBalance_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Int @fdc_generated(from: "User.currencyBalance", purpose: QUERY_SUM)
  """
  ✨ Average the `currencyBalance` field in the `User` table.
  """
  currencyBalance_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "User.currencyBalance", purpose: QUERY_AVG)
  """
  ✨ Minimum of the `createdAt` field in the `User` table.
  """
  createdAt_min: Timestamp @fdc_generated(from: "User.createdAt", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `currencyBalance` field in the `User` table.
  """
  currencyBalance_min: Int @fdc_generated(from: "User.currencyBalance", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `createdAt` field in the `User` table.
  """
  createdAt_max: Timestamp @fdc_generated(from: "User.createdAt", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `currencyBalance` field in the `User` table.
  """
  currencyBalance_max: Int @fdc_generated(from: "User.currencyBalance", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "User.id", purpose: GLOBAL_ID)
}
